/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionQuitter;
    QAction *actionA_propos;
    QAction *actionTerminal;
    QAction *actionServos;
    QWidget *centralwidget;
    QGroupBox *groupBox;
    QPushButton *Telnet_Connect;
    QLineEdit *Telnet_IP;
    QLineEdit *Telnet_Port;
    QLabel *label;
    QLabel *label_2;
    QGroupBox *groupBox_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QComboBox *Serial_Baudrate;
    QComboBox *Serial_Data_Bits;
    QComboBox *Serial_Parity;
    QComboBox *Serial_Stop_Bits;
    QComboBox *Serial_Flow_Control;
    QComboBox *Serial_Port;
    QPushButton *Serial_Connect;
    QGroupBox *groupBox_3;
    QPushButton *pushButtonSd;
    QPushButton *pushButton_5;
    QPushButton *pushButtonStopMotor;
    QPushButton *pushButtonReset;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButtonQuit;
    QTabWidget *tabWidget;
    QWidget *tab;
    QGroupBox *groupBox_4;
    QPushButton *pushButton_Command_Terminal_1;
    QLineEdit *Command_Terminal_1;
    QLineEdit *Command_Terminal_2;
    QLineEdit *Command_Terminal_3;
    QLineEdit *Command_Terminal_4;
    QLineEdit *Command_Terminal_5;
    QLineEdit *Command_Terminal_6;
    QLineEdit *Command_Terminal_7;
    QLineEdit *Command_Terminal_9;
    QLineEdit *Command_Terminal_8;
    QLineEdit *Command_Terminal_10;
    QLineEdit *Command_Terminal_11;
    QPushButton *pushButton_Command_Terminal_2;
    QPushButton *pushButton_Command_Terminal_3;
    QPushButton *pushButton_Command_Terminal_4;
    QPushButton *pushButton_Command_Terminal_5;
    QPushButton *pushButton_Command_Terminal_6;
    QPushButton *pushButton_Command_Terminal_7;
    QPushButton *pushButton_Command_Terminal_8;
    QPushButton *pushButton_Command_Terminal_9;
    QPushButton *pushButton_Command_Terminal_10;
    QPushButton *pushButton_Command_Terminal_11;
    QTextEdit *textEdit;
    QWidget *tab_6;
    QWidget *tab_2;
    QWidget *tab_4;
    QGroupBox *groupBox_6;
    QTextBrowser *textBrowser;
    QGroupBox *groupBox_7;
    QLabel *label_29;
    QLineEdit *lineEdit_14;
    QLabel *label_30;
    QLineEdit *lineEdit_15;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QGroupBox *groupBox_8;
    QRadioButton *radioButton_7;
    QRadioButton *radioButton_4;
    QRadioButton *radioButton;
    QRadioButton *radioButton_5;
    QRadioButton *radioButton_3;
    QRadioButton *radioButton_2;
    QRadioButton *radioButton_6;
    QPushButton *pushButton_66;
    QWidget *tab_3;
    QGroupBox *groupBox_5;
    QLabel *label_17;
    QLabel *label_15;
    QLabel *label_28;
    QLabel *label_24;
    QLabel *label_27;
    QLabel *label_19;
    QLabel *label_25;
    QLabel *label_10;
    QLabel *label_23;
    QLabel *label_11;
    QLabel *label_16;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_18;
    QSlider *Servo_Index1;
    QLabel *label_14;
    QLabel *label_20;
    QLabel *label_26;
    QLabel *label_9;
    QLabel *label_21;
    QLabel *label_22;
    QSlider *horizontalSlider;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QPushButton *pushButton_28;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QSlider *Servo_Index1_2;
    QSlider *Servo_Index1_3;
    QSlider *Servo_Index1_4;
    QSlider *horizontalSlider_2;
    QSlider *Servo_Index1_5;
    QSlider *Servo_Index1_6;
    QSlider *Servo_Index1_7;
    QSlider *horizontalSlider_3;
    QSlider *Servo_Index1_8;
    QSlider *Servo_Index1_9;
    QSlider *Servo_Index1_10;
    QSlider *Servo_Index1_11;
    QSlider *Servo_Index1_12;
    QSlider *horizontalSlider_4;
    QSlider *Servo_Index1_13;
    QSlider *Servo_Index1_14;
    QSlider *Servo_Index1_15;
    QSlider *Servo_Index1_16;
    QWidget *tab_5;
    QWidget *tab_7;
    QWidget *tab_8;
    QMenuBar *menubar;
    QMenu *menuFichier;
    QMenu *menu_Aide;
    QMenu *menuConfiguration;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1268, 725);
        actionQuitter = new QAction(MainWindow);
        actionQuitter->setObjectName(QString::fromUtf8("actionQuitter"));
        actionA_propos = new QAction(MainWindow);
        actionA_propos->setObjectName(QString::fromUtf8("actionA_propos"));
        actionTerminal = new QAction(MainWindow);
        actionTerminal->setObjectName(QString::fromUtf8("actionTerminal"));
        actionServos = new QAction(MainWindow);
        actionServos->setObjectName(QString::fromUtf8("actionServos"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        groupBox = new QGroupBox(centralwidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(0, 0, 181, 111));
        Telnet_Connect = new QPushButton(groupBox);
        Telnet_Connect->setObjectName(QString::fromUtf8("Telnet_Connect"));
        Telnet_Connect->setGeometry(QRect(50, 80, 111, 23));
        Telnet_Connect->setStyleSheet(QString::fromUtf8("color: rgb(170, 85, 127);"));
        Telnet_IP = new QLineEdit(groupBox);
        Telnet_IP->setObjectName(QString::fromUtf8("Telnet_IP"));
        Telnet_IP->setGeometry(QRect(50, 20, 113, 20));
        Telnet_IP->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Telnet_Port = new QLineEdit(groupBox);
        Telnet_Port->setObjectName(QString::fromUtf8("Telnet_Port"));
        Telnet_Port->setGeometry(QRect(50, 50, 113, 20));
        Telnet_Port->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 47, 13));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 50, 47, 13));
        groupBox_2 = new QGroupBox(centralwidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 110, 181, 231));
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 20, 61, 16));
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(10, 50, 61, 16));
        label_5 = new QLabel(groupBox_2);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 80, 61, 16));
        label_6 = new QLabel(groupBox_2);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 110, 47, 13));
        label_7 = new QLabel(groupBox_2);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 140, 47, 13));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 170, 47, 13));
        Serial_Baudrate = new QComboBox(groupBox_2);
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->addItem(QString());
        Serial_Baudrate->setObjectName(QString::fromUtf8("Serial_Baudrate"));
        Serial_Baudrate->setGeometry(QRect(90, 50, 81, 22));
        Serial_Baudrate->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Data_Bits = new QComboBox(groupBox_2);
        Serial_Data_Bits->addItem(QString());
        Serial_Data_Bits->addItem(QString());
        Serial_Data_Bits->setObjectName(QString::fromUtf8("Serial_Data_Bits"));
        Serial_Data_Bits->setGeometry(QRect(90, 80, 81, 22));
        Serial_Data_Bits->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Parity = new QComboBox(groupBox_2);
        Serial_Parity->addItem(QString());
        Serial_Parity->addItem(QString());
        Serial_Parity->addItem(QString());
        Serial_Parity->addItem(QString());
        Serial_Parity->addItem(QString());
        Serial_Parity->setObjectName(QString::fromUtf8("Serial_Parity"));
        Serial_Parity->setGeometry(QRect(90, 110, 81, 22));
        Serial_Parity->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Stop_Bits = new QComboBox(groupBox_2);
        Serial_Stop_Bits->addItem(QString());
        Serial_Stop_Bits->addItem(QString());
        Serial_Stop_Bits->addItem(QString());
        Serial_Stop_Bits->setObjectName(QString::fromUtf8("Serial_Stop_Bits"));
        Serial_Stop_Bits->setGeometry(QRect(90, 140, 81, 22));
        Serial_Stop_Bits->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Flow_Control = new QComboBox(groupBox_2);
        Serial_Flow_Control->addItem(QString());
        Serial_Flow_Control->setObjectName(QString::fromUtf8("Serial_Flow_Control"));
        Serial_Flow_Control->setGeometry(QRect(90, 170, 81, 22));
        Serial_Flow_Control->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Port = new QComboBox(groupBox_2);
        Serial_Port->addItem(QString());
        Serial_Port->addItem(QString());
        Serial_Port->setObjectName(QString::fromUtf8("Serial_Port"));
        Serial_Port->setGeometry(QRect(90, 20, 81, 22));
        Serial_Port->setStyleSheet(QString::fromUtf8("background-color: rgb(211, 212, 255);"));
        Serial_Connect = new QPushButton(groupBox_2);
        Serial_Connect->setObjectName(QString::fromUtf8("Serial_Connect"));
        Serial_Connect->setGeometry(QRect(50, 200, 71, 23));
        Serial_Connect->setStyleSheet(QString::fromUtf8("color: rgb(170, 85, 127);"));
        groupBox_3 = new QGroupBox(centralwidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(0, 360, 181, 321));
        pushButtonSd = new QPushButton(groupBox_3);
        pushButtonSd->setObjectName(QString::fromUtf8("pushButtonSd"));
        pushButtonSd->setGeometry(QRect(10, 60, 71, 23));
        pushButtonSd->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButton_5 = new QPushButton(groupBox_3);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(10, 90, 71, 23));
        pushButton_5->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButtonStopMotor = new QPushButton(groupBox_3);
        pushButtonStopMotor->setObjectName(QString::fromUtf8("pushButtonStopMotor"));
        pushButtonStopMotor->setGeometry(QRect(10, 30, 71, 23));
        pushButtonStopMotor->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButtonReset = new QPushButton(groupBox_3);
        pushButtonReset->setObjectName(QString::fromUtf8("pushButtonReset"));
        pushButtonReset->setGeometry(QRect(100, 30, 71, 23));
        pushButtonReset->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButton_19 = new QPushButton(groupBox_3);
        pushButton_19->setObjectName(QString::fromUtf8("pushButton_19"));
        pushButton_19->setGeometry(QRect(100, 60, 71, 23));
        pushButton_19->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButton_20 = new QPushButton(groupBox_3);
        pushButton_20->setObjectName(QString::fromUtf8("pushButton_20"));
        pushButton_20->setGeometry(QRect(100, 90, 71, 23));
        pushButton_20->setStyleSheet(QString::fromUtf8("color: rgb(170, 0, 127);"));
        pushButtonQuit = new QPushButton(groupBox_3);
        pushButtonQuit->setObjectName(QString::fromUtf8("pushButtonQuit"));
        pushButtonQuit->setGeometry(QRect(50, 260, 75, 23));
        pushButtonQuit->setStyleSheet(QString::fromUtf8("color: rgb(170, 85, 127);"));
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(190, 10, 1071, 671));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        groupBox_4 = new QGroupBox(tab);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(0, -20, 231, 621));
        pushButton_Command_Terminal_1 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_1->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_1"));
        pushButton_Command_Terminal_1->setGeometry(QRect(170, 30, 51, 23));
        Command_Terminal_1 = new QLineEdit(groupBox_4);
        Command_Terminal_1->setObjectName(QString::fromUtf8("Command_Terminal_1"));
        Command_Terminal_1->setGeometry(QRect(10, 30, 141, 20));
        Command_Terminal_2 = new QLineEdit(groupBox_4);
        Command_Terminal_2->setObjectName(QString::fromUtf8("Command_Terminal_2"));
        Command_Terminal_2->setGeometry(QRect(10, 60, 141, 20));
        Command_Terminal_3 = new QLineEdit(groupBox_4);
        Command_Terminal_3->setObjectName(QString::fromUtf8("Command_Terminal_3"));
        Command_Terminal_3->setGeometry(QRect(10, 90, 141, 20));
        Command_Terminal_4 = new QLineEdit(groupBox_4);
        Command_Terminal_4->setObjectName(QString::fromUtf8("Command_Terminal_4"));
        Command_Terminal_4->setGeometry(QRect(10, 120, 141, 20));
        Command_Terminal_5 = new QLineEdit(groupBox_4);
        Command_Terminal_5->setObjectName(QString::fromUtf8("Command_Terminal_5"));
        Command_Terminal_5->setGeometry(QRect(10, 150, 141, 20));
        Command_Terminal_6 = new QLineEdit(groupBox_4);
        Command_Terminal_6->setObjectName(QString::fromUtf8("Command_Terminal_6"));
        Command_Terminal_6->setGeometry(QRect(10, 180, 141, 20));
        Command_Terminal_7 = new QLineEdit(groupBox_4);
        Command_Terminal_7->setObjectName(QString::fromUtf8("Command_Terminal_7"));
        Command_Terminal_7->setGeometry(QRect(10, 210, 141, 20));
        Command_Terminal_9 = new QLineEdit(groupBox_4);
        Command_Terminal_9->setObjectName(QString::fromUtf8("Command_Terminal_9"));
        Command_Terminal_9->setGeometry(QRect(10, 270, 141, 20));
        Command_Terminal_8 = new QLineEdit(groupBox_4);
        Command_Terminal_8->setObjectName(QString::fromUtf8("Command_Terminal_8"));
        Command_Terminal_8->setGeometry(QRect(10, 240, 141, 20));
        Command_Terminal_10 = new QLineEdit(groupBox_4);
        Command_Terminal_10->setObjectName(QString::fromUtf8("Command_Terminal_10"));
        Command_Terminal_10->setGeometry(QRect(10, 300, 141, 20));
        Command_Terminal_11 = new QLineEdit(groupBox_4);
        Command_Terminal_11->setObjectName(QString::fromUtf8("Command_Terminal_11"));
        Command_Terminal_11->setGeometry(QRect(10, 330, 141, 20));
        pushButton_Command_Terminal_2 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_2->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_2"));
        pushButton_Command_Terminal_2->setGeometry(QRect(170, 60, 51, 23));
        pushButton_Command_Terminal_3 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_3->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_3"));
        pushButton_Command_Terminal_3->setGeometry(QRect(170, 90, 51, 23));
        pushButton_Command_Terminal_4 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_4->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_4"));
        pushButton_Command_Terminal_4->setGeometry(QRect(170, 120, 51, 23));
        pushButton_Command_Terminal_5 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_5->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_5"));
        pushButton_Command_Terminal_5->setGeometry(QRect(170, 150, 51, 23));
        pushButton_Command_Terminal_6 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_6->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_6"));
        pushButton_Command_Terminal_6->setGeometry(QRect(170, 180, 51, 23));
        pushButton_Command_Terminal_7 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_7->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_7"));
        pushButton_Command_Terminal_7->setGeometry(QRect(170, 210, 51, 23));
        pushButton_Command_Terminal_8 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_8->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_8"));
        pushButton_Command_Terminal_8->setGeometry(QRect(170, 240, 51, 23));
        pushButton_Command_Terminal_9 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_9->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_9"));
        pushButton_Command_Terminal_9->setGeometry(QRect(170, 270, 51, 23));
        pushButton_Command_Terminal_10 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_10->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_10"));
        pushButton_Command_Terminal_10->setGeometry(QRect(170, 300, 51, 23));
        pushButton_Command_Terminal_11 = new QPushButton(groupBox_4);
        pushButton_Command_Terminal_11->setObjectName(QString::fromUtf8("pushButton_Command_Terminal_11"));
        pushButton_Command_Terminal_11->setGeometry(QRect(170, 330, 51, 23));
        textEdit = new QTextEdit(tab);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(240, 10, 831, 621));
        textEdit->setStyleSheet(QString::fromUtf8("background-color: rgb(27, 27, 27);\n"
"color: rgb(255, 0, 0);"));
        tabWidget->addTab(tab, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        tabWidget->addTab(tab_6, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tabWidget->addTab(tab_2, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        groupBox_6 = new QGroupBox(tab_4);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(20, 20, 441, 621));
        textBrowser = new QTextBrowser(groupBox_6);
        textBrowser->setObjectName(QString::fromUtf8("textBrowser"));
        textBrowser->setGeometry(QRect(20, 30, 391, 571));
        groupBox_7 = new QGroupBox(tab_4);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(480, 20, 461, 621));
        label_29 = new QLabel(groupBox_7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(20, 260, 47, 13));
        lineEdit_14 = new QLineEdit(groupBox_7);
        lineEdit_14->setObjectName(QString::fromUtf8("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(90, 260, 113, 20));
        label_30 = new QLabel(groupBox_7);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(20, 290, 47, 13));
        lineEdit_15 = new QLineEdit(groupBox_7);
        lineEdit_15->setObjectName(QString::fromUtf8("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(90, 290, 113, 20));
        pushButton_22 = new QPushButton(groupBox_7);
        pushButton_22->setObjectName(QString::fromUtf8("pushButton_22"));
        pushButton_22->setGeometry(QRect(94, 360, 81, 23));
        pushButton_23 = new QPushButton(groupBox_7);
        pushButton_23->setObjectName(QString::fromUtf8("pushButton_23"));
        pushButton_23->setGeometry(QRect(94, 390, 81, 23));
        pushButton_24 = new QPushButton(groupBox_7);
        pushButton_24->setObjectName(QString::fromUtf8("pushButton_24"));
        pushButton_24->setGeometry(QRect(200, 360, 81, 23));
        pushButton_25 = new QPushButton(groupBox_7);
        pushButton_25->setObjectName(QString::fromUtf8("pushButton_25"));
        pushButton_25->setGeometry(QRect(200, 390, 81, 23));
        groupBox_8 = new QGroupBox(groupBox_7);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(30, 30, 101, 171));
        radioButton_7 = new QRadioButton(groupBox_8);
        radioButton_7->setObjectName(QString::fromUtf8("radioButton_7"));
        radioButton_7->setGeometry(QRect(20, 140, 82, 17));
        radioButton_7->setChecked(true);
        radioButton_4 = new QRadioButton(groupBox_8);
        radioButton_4->setObjectName(QString::fromUtf8("radioButton_4"));
        radioButton_4->setGeometry(QRect(20, 80, 82, 17));
        radioButton = new QRadioButton(groupBox_8);
        radioButton->setObjectName(QString::fromUtf8("radioButton"));
        radioButton->setGeometry(QRect(20, 20, 82, 17));
        radioButton_5 = new QRadioButton(groupBox_8);
        radioButton_5->setObjectName(QString::fromUtf8("radioButton_5"));
        radioButton_5->setGeometry(QRect(20, 100, 82, 17));
        radioButton_3 = new QRadioButton(groupBox_8);
        radioButton_3->setObjectName(QString::fromUtf8("radioButton_3"));
        radioButton_3->setGeometry(QRect(20, 60, 82, 17));
        radioButton_2 = new QRadioButton(groupBox_8);
        radioButton_2->setObjectName(QString::fromUtf8("radioButton_2"));
        radioButton_2->setGeometry(QRect(20, 40, 82, 17));
        radioButton_6 = new QRadioButton(groupBox_8);
        radioButton_6->setObjectName(QString::fromUtf8("radioButton_6"));
        radioButton_6->setGeometry(QRect(20, 120, 82, 17));
        pushButton_66 = new QPushButton(groupBox_7);
        pushButton_66->setObjectName(QString::fromUtf8("pushButton_66"));
        pushButton_66->setGeometry(QRect(200, 450, 81, 23));
        tabWidget->addTab(tab_4, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        groupBox_5 = new QGroupBox(tab_3);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 10, 661, 631));
        label_17 = new QLabel(groupBox_5);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(30, 260, 81, 16));
        label_15 = new QLabel(groupBox_5);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(30, 200, 81, 16));
        label_28 = new QLabel(groupBox_5);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(30, 590, 81, 16));
        label_24 = new QLabel(groupBox_5);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(30, 470, 81, 16));
        label_27 = new QLabel(groupBox_5);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(30, 560, 81, 16));
        label_19 = new QLabel(groupBox_5);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(30, 320, 81, 16));
        label_25 = new QLabel(groupBox_5);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(30, 500, 81, 16));
        label_10 = new QLabel(groupBox_5);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(30, 50, 81, 16));
        label_23 = new QLabel(groupBox_5);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(30, 440, 81, 16));
        label_11 = new QLabel(groupBox_5);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(30, 80, 81, 16));
        label_16 = new QLabel(groupBox_5);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(30, 230, 81, 16));
        label_12 = new QLabel(groupBox_5);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(30, 110, 81, 16));
        label_13 = new QLabel(groupBox_5);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(30, 140, 81, 16));
        label_18 = new QLabel(groupBox_5);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(30, 290, 81, 16));
        Servo_Index1 = new QSlider(groupBox_5);
        Servo_Index1->setObjectName(QString::fromUtf8("Servo_Index1"));
        Servo_Index1->setGeometry(QRect(120, 50, 311, 22));
        Servo_Index1->setMaximum(4096);
        Servo_Index1->setValue(2048);
        Servo_Index1->setOrientation(Qt::Horizontal);
        label_14 = new QLabel(groupBox_5);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(30, 170, 81, 16));
        label_20 = new QLabel(groupBox_5);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(30, 350, 81, 16));
        label_26 = new QLabel(groupBox_5);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(30, 530, 81, 16));
        label_9 = new QLabel(groupBox_5);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(30, 20, 81, 16));
        label_21 = new QLabel(groupBox_5);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(30, 380, 81, 16));
        label_22 = new QLabel(groupBox_5);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(30, 410, 81, 16));
        horizontalSlider = new QSlider(groupBox_5);
        horizontalSlider->setObjectName(QString::fromUtf8("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(120, 20, 311, 22));
        horizontalSlider->setMaximum(4096);
        horizontalSlider->setValue(2048);
        horizontalSlider->setOrientation(Qt::Horizontal);
        pushButton_26 = new QPushButton(groupBox_5);
        pushButton_26->setObjectName(QString::fromUtf8("pushButton_26"));
        pushButton_26->setGeometry(QRect(450, 20, 75, 23));
        pushButton_27 = new QPushButton(groupBox_5);
        pushButton_27->setObjectName(QString::fromUtf8("pushButton_27"));
        pushButton_27->setGeometry(QRect(540, 20, 75, 23));
        pushButton_28 = new QPushButton(groupBox_5);
        pushButton_28->setObjectName(QString::fromUtf8("pushButton_28"));
        pushButton_28->setGeometry(QRect(450, 50, 75, 23));
        pushButton_29 = new QPushButton(groupBox_5);
        pushButton_29->setObjectName(QString::fromUtf8("pushButton_29"));
        pushButton_29->setGeometry(QRect(540, 50, 75, 23));
        pushButton_30 = new QPushButton(groupBox_5);
        pushButton_30->setObjectName(QString::fromUtf8("pushButton_30"));
        pushButton_30->setGeometry(QRect(450, 80, 75, 23));
        pushButton_31 = new QPushButton(groupBox_5);
        pushButton_31->setObjectName(QString::fromUtf8("pushButton_31"));
        pushButton_31->setGeometry(QRect(540, 80, 75, 23));
        pushButton_32 = new QPushButton(groupBox_5);
        pushButton_32->setObjectName(QString::fromUtf8("pushButton_32"));
        pushButton_32->setGeometry(QRect(450, 110, 75, 23));
        pushButton_33 = new QPushButton(groupBox_5);
        pushButton_33->setObjectName(QString::fromUtf8("pushButton_33"));
        pushButton_33->setGeometry(QRect(540, 110, 75, 23));
        pushButton_34 = new QPushButton(groupBox_5);
        pushButton_34->setObjectName(QString::fromUtf8("pushButton_34"));
        pushButton_34->setGeometry(QRect(450, 140, 75, 23));
        pushButton_35 = new QPushButton(groupBox_5);
        pushButton_35->setObjectName(QString::fromUtf8("pushButton_35"));
        pushButton_35->setGeometry(QRect(540, 140, 75, 23));
        pushButton_36 = new QPushButton(groupBox_5);
        pushButton_36->setObjectName(QString::fromUtf8("pushButton_36"));
        pushButton_36->setGeometry(QRect(450, 260, 75, 23));
        pushButton_37 = new QPushButton(groupBox_5);
        pushButton_37->setObjectName(QString::fromUtf8("pushButton_37"));
        pushButton_37->setGeometry(QRect(540, 200, 75, 23));
        pushButton_38 = new QPushButton(groupBox_5);
        pushButton_38->setObjectName(QString::fromUtf8("pushButton_38"));
        pushButton_38->setGeometry(QRect(540, 260, 75, 23));
        pushButton_39 = new QPushButton(groupBox_5);
        pushButton_39->setObjectName(QString::fromUtf8("pushButton_39"));
        pushButton_39->setGeometry(QRect(540, 290, 75, 23));
        pushButton_40 = new QPushButton(groupBox_5);
        pushButton_40->setObjectName(QString::fromUtf8("pushButton_40"));
        pushButton_40->setGeometry(QRect(450, 200, 75, 23));
        pushButton_41 = new QPushButton(groupBox_5);
        pushButton_41->setObjectName(QString::fromUtf8("pushButton_41"));
        pushButton_41->setGeometry(QRect(450, 230, 75, 23));
        pushButton_42 = new QPushButton(groupBox_5);
        pushButton_42->setObjectName(QString::fromUtf8("pushButton_42"));
        pushButton_42->setGeometry(QRect(540, 230, 75, 23));
        pushButton_43 = new QPushButton(groupBox_5);
        pushButton_43->setObjectName(QString::fromUtf8("pushButton_43"));
        pushButton_43->setGeometry(QRect(450, 170, 75, 23));
        pushButton_44 = new QPushButton(groupBox_5);
        pushButton_44->setObjectName(QString::fromUtf8("pushButton_44"));
        pushButton_44->setGeometry(QRect(450, 290, 75, 23));
        pushButton_45 = new QPushButton(groupBox_5);
        pushButton_45->setObjectName(QString::fromUtf8("pushButton_45"));
        pushButton_45->setGeometry(QRect(540, 170, 75, 23));
        pushButton_46 = new QPushButton(groupBox_5);
        pushButton_46->setObjectName(QString::fromUtf8("pushButton_46"));
        pushButton_46->setGeometry(QRect(450, 410, 75, 23));
        pushButton_47 = new QPushButton(groupBox_5);
        pushButton_47->setObjectName(QString::fromUtf8("pushButton_47"));
        pushButton_47->setGeometry(QRect(540, 350, 75, 23));
        pushButton_48 = new QPushButton(groupBox_5);
        pushButton_48->setObjectName(QString::fromUtf8("pushButton_48"));
        pushButton_48->setGeometry(QRect(540, 410, 75, 23));
        pushButton_49 = new QPushButton(groupBox_5);
        pushButton_49->setObjectName(QString::fromUtf8("pushButton_49"));
        pushButton_49->setGeometry(QRect(540, 440, 75, 23));
        pushButton_50 = new QPushButton(groupBox_5);
        pushButton_50->setObjectName(QString::fromUtf8("pushButton_50"));
        pushButton_50->setGeometry(QRect(450, 350, 75, 23));
        pushButton_51 = new QPushButton(groupBox_5);
        pushButton_51->setObjectName(QString::fromUtf8("pushButton_51"));
        pushButton_51->setGeometry(QRect(450, 380, 75, 23));
        pushButton_52 = new QPushButton(groupBox_5);
        pushButton_52->setObjectName(QString::fromUtf8("pushButton_52"));
        pushButton_52->setGeometry(QRect(540, 380, 75, 23));
        pushButton_53 = new QPushButton(groupBox_5);
        pushButton_53->setObjectName(QString::fromUtf8("pushButton_53"));
        pushButton_53->setGeometry(QRect(450, 320, 75, 23));
        pushButton_54 = new QPushButton(groupBox_5);
        pushButton_54->setObjectName(QString::fromUtf8("pushButton_54"));
        pushButton_54->setGeometry(QRect(450, 440, 75, 23));
        pushButton_55 = new QPushButton(groupBox_5);
        pushButton_55->setObjectName(QString::fromUtf8("pushButton_55"));
        pushButton_55->setGeometry(QRect(540, 320, 75, 23));
        pushButton_56 = new QPushButton(groupBox_5);
        pushButton_56->setObjectName(QString::fromUtf8("pushButton_56"));
        pushButton_56->setGeometry(QRect(450, 560, 75, 23));
        pushButton_57 = new QPushButton(groupBox_5);
        pushButton_57->setObjectName(QString::fromUtf8("pushButton_57"));
        pushButton_57->setGeometry(QRect(540, 500, 75, 23));
        pushButton_58 = new QPushButton(groupBox_5);
        pushButton_58->setObjectName(QString::fromUtf8("pushButton_58"));
        pushButton_58->setGeometry(QRect(540, 560, 75, 23));
        pushButton_59 = new QPushButton(groupBox_5);
        pushButton_59->setObjectName(QString::fromUtf8("pushButton_59"));
        pushButton_59->setGeometry(QRect(540, 590, 75, 23));
        pushButton_60 = new QPushButton(groupBox_5);
        pushButton_60->setObjectName(QString::fromUtf8("pushButton_60"));
        pushButton_60->setGeometry(QRect(450, 500, 75, 23));
        pushButton_61 = new QPushButton(groupBox_5);
        pushButton_61->setObjectName(QString::fromUtf8("pushButton_61"));
        pushButton_61->setGeometry(QRect(450, 530, 75, 23));
        pushButton_62 = new QPushButton(groupBox_5);
        pushButton_62->setObjectName(QString::fromUtf8("pushButton_62"));
        pushButton_62->setGeometry(QRect(540, 530, 75, 23));
        pushButton_63 = new QPushButton(groupBox_5);
        pushButton_63->setObjectName(QString::fromUtf8("pushButton_63"));
        pushButton_63->setGeometry(QRect(450, 470, 75, 23));
        pushButton_64 = new QPushButton(groupBox_5);
        pushButton_64->setObjectName(QString::fromUtf8("pushButton_64"));
        pushButton_64->setGeometry(QRect(450, 590, 75, 23));
        pushButton_65 = new QPushButton(groupBox_5);
        pushButton_65->setObjectName(QString::fromUtf8("pushButton_65"));
        pushButton_65->setGeometry(QRect(540, 470, 75, 23));
        Servo_Index1_2 = new QSlider(groupBox_5);
        Servo_Index1_2->setObjectName(QString::fromUtf8("Servo_Index1_2"));
        Servo_Index1_2->setGeometry(QRect(120, 80, 311, 22));
        Servo_Index1_2->setMaximum(4096);
        Servo_Index1_2->setValue(2048);
        Servo_Index1_2->setOrientation(Qt::Horizontal);
        Servo_Index1_3 = new QSlider(groupBox_5);
        Servo_Index1_3->setObjectName(QString::fromUtf8("Servo_Index1_3"));
        Servo_Index1_3->setGeometry(QRect(120, 110, 311, 22));
        Servo_Index1_3->setMaximum(4096);
        Servo_Index1_3->setValue(2048);
        Servo_Index1_3->setOrientation(Qt::Horizontal);
        Servo_Index1_4 = new QSlider(groupBox_5);
        Servo_Index1_4->setObjectName(QString::fromUtf8("Servo_Index1_4"));
        Servo_Index1_4->setGeometry(QRect(120, 170, 311, 22));
        Servo_Index1_4->setMaximum(4096);
        Servo_Index1_4->setValue(2048);
        Servo_Index1_4->setOrientation(Qt::Horizontal);
        horizontalSlider_2 = new QSlider(groupBox_5);
        horizontalSlider_2->setObjectName(QString::fromUtf8("horizontalSlider_2"));
        horizontalSlider_2->setGeometry(QRect(120, 140, 311, 22));
        horizontalSlider_2->setMaximum(4096);
        horizontalSlider_2->setValue(2048);
        horizontalSlider_2->setOrientation(Qt::Horizontal);
        Servo_Index1_5 = new QSlider(groupBox_5);
        Servo_Index1_5->setObjectName(QString::fromUtf8("Servo_Index1_5"));
        Servo_Index1_5->setGeometry(QRect(120, 230, 311, 22));
        Servo_Index1_5->setMaximum(4096);
        Servo_Index1_5->setValue(2048);
        Servo_Index1_5->setOrientation(Qt::Horizontal);
        Servo_Index1_6 = new QSlider(groupBox_5);
        Servo_Index1_6->setObjectName(QString::fromUtf8("Servo_Index1_6"));
        Servo_Index1_6->setGeometry(QRect(120, 200, 311, 22));
        Servo_Index1_6->setMaximum(4096);
        Servo_Index1_6->setValue(2048);
        Servo_Index1_6->setOrientation(Qt::Horizontal);
        Servo_Index1_7 = new QSlider(groupBox_5);
        Servo_Index1_7->setObjectName(QString::fromUtf8("Servo_Index1_7"));
        Servo_Index1_7->setGeometry(QRect(120, 290, 311, 22));
        Servo_Index1_7->setMaximum(4096);
        Servo_Index1_7->setValue(2048);
        Servo_Index1_7->setOrientation(Qt::Horizontal);
        horizontalSlider_3 = new QSlider(groupBox_5);
        horizontalSlider_3->setObjectName(QString::fromUtf8("horizontalSlider_3"));
        horizontalSlider_3->setGeometry(QRect(120, 260, 311, 22));
        horizontalSlider_3->setMaximum(4096);
        horizontalSlider_3->setValue(2048);
        horizontalSlider_3->setOrientation(Qt::Horizontal);
        Servo_Index1_8 = new QSlider(groupBox_5);
        Servo_Index1_8->setObjectName(QString::fromUtf8("Servo_Index1_8"));
        Servo_Index1_8->setGeometry(QRect(120, 350, 311, 22));
        Servo_Index1_8->setMaximum(4096);
        Servo_Index1_8->setValue(2048);
        Servo_Index1_8->setOrientation(Qt::Horizontal);
        Servo_Index1_9 = new QSlider(groupBox_5);
        Servo_Index1_9->setObjectName(QString::fromUtf8("Servo_Index1_9"));
        Servo_Index1_9->setGeometry(QRect(120, 320, 311, 22));
        Servo_Index1_9->setMaximum(4096);
        Servo_Index1_9->setValue(2048);
        Servo_Index1_9->setOrientation(Qt::Horizontal);
        Servo_Index1_10 = new QSlider(groupBox_5);
        Servo_Index1_10->setObjectName(QString::fromUtf8("Servo_Index1_10"));
        Servo_Index1_10->setGeometry(QRect(120, 500, 311, 22));
        Servo_Index1_10->setMaximum(4096);
        Servo_Index1_10->setValue(2048);
        Servo_Index1_10->setOrientation(Qt::Horizontal);
        Servo_Index1_11 = new QSlider(groupBox_5);
        Servo_Index1_11->setObjectName(QString::fromUtf8("Servo_Index1_11"));
        Servo_Index1_11->setGeometry(QRect(120, 530, 311, 22));
        Servo_Index1_11->setMaximum(4096);
        Servo_Index1_11->setValue(2048);
        Servo_Index1_11->setOrientation(Qt::Horizontal);
        Servo_Index1_12 = new QSlider(groupBox_5);
        Servo_Index1_12->setObjectName(QString::fromUtf8("Servo_Index1_12"));
        Servo_Index1_12->setGeometry(QRect(120, 410, 311, 22));
        Servo_Index1_12->setMaximum(4096);
        Servo_Index1_12->setValue(2048);
        Servo_Index1_12->setOrientation(Qt::Horizontal);
        horizontalSlider_4 = new QSlider(groupBox_5);
        horizontalSlider_4->setObjectName(QString::fromUtf8("horizontalSlider_4"));
        horizontalSlider_4->setGeometry(QRect(120, 440, 311, 22));
        horizontalSlider_4->setMaximum(4096);
        horizontalSlider_4->setValue(2048);
        horizontalSlider_4->setOrientation(Qt::Horizontal);
        Servo_Index1_13 = new QSlider(groupBox_5);
        Servo_Index1_13->setObjectName(QString::fromUtf8("Servo_Index1_13"));
        Servo_Index1_13->setGeometry(QRect(120, 380, 311, 22));
        Servo_Index1_13->setMaximum(4096);
        Servo_Index1_13->setValue(2048);
        Servo_Index1_13->setOrientation(Qt::Horizontal);
        Servo_Index1_14 = new QSlider(groupBox_5);
        Servo_Index1_14->setObjectName(QString::fromUtf8("Servo_Index1_14"));
        Servo_Index1_14->setGeometry(QRect(120, 470, 311, 22));
        Servo_Index1_14->setMaximum(4096);
        Servo_Index1_14->setValue(2048);
        Servo_Index1_14->setOrientation(Qt::Horizontal);
        Servo_Index1_15 = new QSlider(groupBox_5);
        Servo_Index1_15->setObjectName(QString::fromUtf8("Servo_Index1_15"));
        Servo_Index1_15->setGeometry(QRect(120, 560, 311, 22));
        Servo_Index1_15->setMaximum(4096);
        Servo_Index1_15->setValue(2048);
        Servo_Index1_15->setOrientation(Qt::Horizontal);
        Servo_Index1_16 = new QSlider(groupBox_5);
        Servo_Index1_16->setObjectName(QString::fromUtf8("Servo_Index1_16"));
        Servo_Index1_16->setGeometry(QRect(120, 590, 311, 22));
        Servo_Index1_16->setMaximum(4096);
        Servo_Index1_16->setValue(2048);
        Servo_Index1_16->setOrientation(Qt::Horizontal);
        tabWidget->addTab(tab_3, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        tabWidget->addTab(tab_5, QString());
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        tabWidget->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        tabWidget->addTab(tab_8, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1268, 21));
        menuFichier = new QMenu(menubar);
        menuFichier->setObjectName(QString::fromUtf8("menuFichier"));
        menu_Aide = new QMenu(menubar);
        menu_Aide->setObjectName(QString::fromUtf8("menu_Aide"));
        menuConfiguration = new QMenu(menubar);
        menuConfiguration->setObjectName(QString::fromUtf8("menuConfiguration"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuFichier->menuAction());
        menubar->addAction(menuConfiguration->menuAction());
        menubar->addAction(menu_Aide->menuAction());
        menuFichier->addAction(actionQuitter);
        menu_Aide->addAction(actionA_propos);
        menuConfiguration->addAction(actionTerminal);
        menuConfiguration->addAction(actionServos);

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Interface Titan", nullptr));
        actionQuitter->setText(QCoreApplication::translate("MainWindow", "Quitter", nullptr));
        actionA_propos->setText(QCoreApplication::translate("MainWindow", "A propos", nullptr));
        actionTerminal->setText(QCoreApplication::translate("MainWindow", "Terminal", nullptr));
        actionServos->setText(QCoreApplication::translate("MainWindow", "Servos", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindow", "Telnet", nullptr));
        Telnet_Connect->setText(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "IP", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Port", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWindow", "Serial", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Serial Port", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "BaudeRate", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Data Bits", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Parity", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Stop bits", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Flow Control", nullptr));
        Serial_Baudrate->setItemText(0, QCoreApplication::translate("MainWindow", "9600", nullptr));
        Serial_Baudrate->setItemText(1, QCoreApplication::translate("MainWindow", "19200", nullptr));
        Serial_Baudrate->setItemText(2, QCoreApplication::translate("MainWindow", "38400", nullptr));
        Serial_Baudrate->setItemText(3, QCoreApplication::translate("MainWindow", "57600", nullptr));
        Serial_Baudrate->setItemText(4, QCoreApplication::translate("MainWindow", "115200", nullptr));
        Serial_Baudrate->setItemText(5, QCoreApplication::translate("MainWindow", "250000", nullptr));

        Serial_Baudrate->setCurrentText(QCoreApplication::translate("MainWindow", "9600", nullptr));
        Serial_Data_Bits->setItemText(0, QCoreApplication::translate("MainWindow", "7", nullptr));
        Serial_Data_Bits->setItemText(1, QCoreApplication::translate("MainWindow", "8", nullptr));

        Serial_Data_Bits->setCurrentText(QCoreApplication::translate("MainWindow", "7", nullptr));
        Serial_Parity->setItemText(0, QCoreApplication::translate("MainWindow", "NoParity", nullptr));
        Serial_Parity->setItemText(1, QCoreApplication::translate("MainWindow", "EvenParity", nullptr));
        Serial_Parity->setItemText(2, QCoreApplication::translate("MainWindow", "OddParity", nullptr));
        Serial_Parity->setItemText(3, QCoreApplication::translate("MainWindow", "SpaceParity", nullptr));
        Serial_Parity->setItemText(4, QCoreApplication::translate("MainWindow", "MarkParity", nullptr));

        Serial_Stop_Bits->setItemText(0, QCoreApplication::translate("MainWindow", "OneStop", nullptr));
        Serial_Stop_Bits->setItemText(1, QCoreApplication::translate("MainWindow", "OneAndHalfStop", nullptr));
        Serial_Stop_Bits->setItemText(2, QCoreApplication::translate("MainWindow", "TwoStop", nullptr));

        Serial_Flow_Control->setItemText(0, QCoreApplication::translate("MainWindow", "NoFlowControl", nullptr));

        Serial_Port->setItemText(0, QCoreApplication::translate("MainWindow", "None", nullptr));
        Serial_Port->setItemText(1, QCoreApplication::translate("MainWindow", "testport", nullptr));

        Serial_Port->setCurrentText(QCoreApplication::translate("MainWindow", "None", nullptr));
        Serial_Connect->setText(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindow", "Emergency Command", nullptr));
        pushButtonSd->setText(QCoreApplication::translate("MainWindow", "Device List", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "PushButton", nullptr));
        pushButtonStopMotor->setText(QCoreApplication::translate("MainWindow", "STOP Motor", nullptr));
        pushButtonReset->setText(QCoreApplication::translate("MainWindow", "RESET", nullptr));
        pushButton_19->setText(QCoreApplication::translate("MainWindow", "PushButton", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "PushButton", nullptr));
        pushButtonQuit->setText(QCoreApplication::translate("MainWindow", "Quitter", nullptr));
        groupBox_4->setTitle(QCoreApplication::translate("MainWindow", "Commande Terminal", nullptr));
        pushButton_Command_Terminal_1->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_2->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_3->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_4->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_5->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_6->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_7->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_8->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_9->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_10->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        pushButton_Command_Terminal_11->setText(QCoreApplication::translate("MainWindow", "->send", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindow", "Terminal", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QCoreApplication::translate("MainWindow", "Tableau de bord", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindow", "Run", nullptr));
        groupBox_6->setTitle(QCoreApplication::translate("MainWindow", "Dump", nullptr));
        groupBox_7->setTitle(QCoreApplication::translate("MainWindow", "Eeprom Control", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Address", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Taille", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Read", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "Read Block", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Write", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "Write Block", nullptr));
        groupBox_8->setTitle(QCoreApplication::translate("MainWindow", " Eeprom Type", nullptr));
        radioButton_7->setText(QCoreApplication::translate("MainWindow", "24C1025", nullptr));
        radioButton_4->setText(QCoreApplication::translate("MainWindow", "24C128", nullptr));
        radioButton->setText(QCoreApplication::translate("MainWindow", "24C16", nullptr));
        radioButton_5->setText(QCoreApplication::translate("MainWindow", "24C256", nullptr));
        radioButton_3->setText(QCoreApplication::translate("MainWindow", "24C64", nullptr));
        radioButton_2->setText(QCoreApplication::translate("MainWindow", "24C32", nullptr));
        radioButton_6->setText(QCoreApplication::translate("MainWindow", "24C512", nullptr));
        pushButton_66->setText(QCoreApplication::translate("MainWindow", "Erase Memory", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QCoreApplication::translate("MainWindow", "Eeprom", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindow", "Servos Controlsl", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Servo Index 8", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Servo Index 6", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Servo Index 19", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Servo Index 15", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Servo Index 18", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Servo Index 10", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Servo Index 16", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Servo Index 1", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Servo Index 14", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Servo Index 2", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Servo Index 7", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Servo Index 3", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Servo Index 4", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Servo Index 9", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Servo Index 5", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Servo Index 11", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Servo Index 17", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Servo Index 0", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Servo Index 12", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Servo Index 13", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_28->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_29->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_32->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_33->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_34->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_35->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_36->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_37->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_38->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_39->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_40->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_41->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_42->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_43->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_44->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_45->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_46->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_47->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_48->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_49->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_50->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_51->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_52->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_53->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_54->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_55->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_56->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_57->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_58->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_59->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_60->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_61->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_62->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        pushButton_63->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_64->setText(QCoreApplication::translate("MainWindow", "Reset", nullptr));
        pushButton_65->setText(QCoreApplication::translate("MainWindow", "Store", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QCoreApplication::translate("MainWindow", "Servos", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QCoreApplication::translate("MainWindow", "Accelerometre", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QCoreApplication::translate("MainWindow", "Power Supply", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QCoreApplication::translate("MainWindow", "LCD", nullptr));
        menuFichier->setTitle(QCoreApplication::translate("MainWindow", "&Fichier", nullptr));
        menu_Aide->setTitle(QCoreApplication::translate("MainWindow", "&Aide", nullptr));
        menuConfiguration->setTitle(QCoreApplication::translate("MainWindow", "Configuration", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
